import turtle as tt
import os
k=eval(input("放大倍数="))
n=eval(input("方格大小="))
tt.delay(0)
t=tt.Pen()
t.hideturtle()
t.pencolor("red")
t.width(n//10+1)
t.speed("fastest")
t.dot(n//4+1,"red")
#画方格、坐标轴
tx=tt.Pen()
tx.hideturtle()
tx.pencolor("black")
tx.width(n//10)
tx.speed("fastest")
tx.penup()
tx.goto(-500,0)
tx.pendown()
tx.goto(500,0)
tx.penup()
ty=tt.Pen()
ty.hideturtle()
ty.pencolor("black")
ty.width(n//10)
ty.speed("fastest")
ty.penup()
ty.goto(0,-500)
ty.pendown()
ty.goto(0,500)
ty.penup()
for x in range(int(-500/n),int(500/n)):
    tx.goto(x*n,0)
    tx.pendown()
    tx.dot(n//4,"black")
    tx.penup()
    ty.goto(0,x*n)
    ty.pendown()
    ty.dot(n//4,"black")
    ty.penup()
    tx.goto(-500,x*n)
    tx.pendown()
    tx.goto(500,x*n)
    tx.penup()
    ty.goto(x*n,-500)
    ty.pendown()
    ty.goto(x*n,500)
    ty.penup()
#函数图像
a=input("请输入方程式(留空以结束):y=")
while a!='':
    t.penup()
    for m in range(-500,501):
      x=m/k/n
      try:
          t.goto(m,int(eval(a)*n*k))
      except Exception as err:
            print(err)
            t.penup()
            continue
      t.pendown()
    a=input("请输入方程式(留空以结束):y=")
end=input("绘制完成，按回车退出")
